# Site settings
title: Young-Geun Choi (최영근)
email: yg_choi@sk.com
description: > # this means to ignore newlines until "baseurl:"
  Young-Geun Choi (최영근), Statistician, PhD.
  Research Scientist at SK Telecom, Seoul, Korea.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://younggeunchoi.github.io" # the base hostname & protocol for your site

# facebook_username: ""
# twitter_username: ""
github_username: "younggeunchoi"

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Research Scientist"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""